# Generated by Django 5.2 on 2025-04-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PikpakAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('access_token', models.TextField(blank=True, verbose_name='访问令牌')),
                ('refresh_token', models.TextField(blank=True, verbose_name='刷新令牌')),
                ('token_expiry', models.DateTimeField(blank=True, null=True, verbose_name='令牌过期时间')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='最近登录')),
            ],
            options={
                'verbose_name': 'PikPak账户',
                'verbose_name_plural': 'PikPak账户',
            },
        ),
        migrations.CreateModel(
            name='PikpakFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255, verbose_name='文件ID')),
                ('name', models.CharField(max_length=255, verbose_name='文件名')),
                ('size', models.BigIntegerField(default=0, verbose_name='大小')),
                ('file_type', models.CharField(max_length=50, verbose_name='类型')),
                ('parent_id', models.CharField(blank=True, max_length=255, verbose_name='父文件夹ID')),
                ('download_url', models.URLField(blank=True, verbose_name='下载URL')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='缩略图URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'PikPak文件',
                'verbose_name_plural': 'PikPak文件',
            },
        ),
    ]
