# Generated by Django 5.2 on 2025-04-14 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pikpak', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pikpakaccount',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pikpakfile',
            options={},
        ),
        migrations.RemoveField(
            model_name='pikpakaccount',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='pikpakfile',
            name='download_url',
        ),
        migrations.RemoveField(
            model_name='pikpakfile',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='pikpakfile',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='pikpakfile',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='pikpakaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pikpakaccount',
            name='webdav_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pikpakaccount',
            name='webdav_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pikpakaccount',
            name='webdav_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pikpakfile',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pikpakfile',
            name='path',
            field=models.TextField(default='/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pikpakfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pikpakaccount',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pikpakaccount',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='pikpakaccount',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pikpakaccount',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pikpakfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pikpakfile',
            name='file_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pikpakfile',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pikpakfile',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='IDMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual_id', models.CharField(max_length=50, unique=True)),
                ('real_path', models.TextField()),
                ('is_directory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['virtual_id'], name='pikpak_idma_virtual_b80514_idx'), models.Index(fields=['real_path'], name='pikpak_idma_real_pa_355ccd_idx')],
            },
        ),
    ]
